### ISSUE TITLE
build fails with dependecy error on LoggerAPI.git

### ISSUE THREAD

**Issue by mpcarl-ibm** [IBM-Swift/TodoList-Redis#6]
Running the build command per the README results in the error:

Cloning https://github.com/IBM-Swift/Kitura-sys.git
HEAD is now at 8207d2c DEVELOPMENT-SNAPSHOT-2016-09-07-a
Resolved version: 0.30.0
error: The dependency graph could not be satisfied (https://github.com/IBM-Swift/LoggerAPI.git)

I have tried changing various dependencies and swift levels, but no luck.

**Comment by tfrank64** [comment]
This no longer seems to be an issue with swift version 3.0.2. Feel free to comment if issue still persists.
